-- ═══════════════════════════════════════════════════════════════════════════
-- 0056_spatial_import_audit.sql
-- Crea   : spatial.import_batches · spatial.import_row_errors
-- Depende de: 0047 (schema), 0049 (sites)
-- Riesgo : bajo · tablas nuevas y vacías
--
-- Es la trazabilidad del importador, y existe para que dos cosas sean imposibles:
--
--   · Que una fila rechazada desaparezca en silencio. Un rechazo invisible produce
--     un catálogo que PARECE completo, y eso es peor que una importación fallida.
--   · Que reimportar el mismo archivo duplique datos. `file_sha256` con índice
--     único sobre los lotes completados lo detecta antes de leer una fila.
--
-- `import_row_errors` es SOLO-AÑADIR: no hay política de UPDATE ni DELETE para el
-- usuario. Un registro de errores editable no es un registro de errores.
-- ═══════════════════════════════════════════════════════════════════════════

CREATE TABLE spatial.import_batches (
    id                uuid         PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id         uuid         NOT NULL REFERENCES core.tenants(id),
    warehouse_id      uuid         NOT NULL,

    source_name       varchar(200) NOT NULL,
    file_sha256       char(64)     NOT NULL,

    rows_read         integer      NOT NULL DEFAULT 0,
    rows_rejected     integer      NOT NULL DEFAULT 0,
    nodes_created     integer      NOT NULL DEFAULT 0,
    bays_created      integer      NOT NULL DEFAULT 0,
    locations_created integer      NOT NULL DEFAULT 0,

    status            varchar(12)  NOT NULL DEFAULT 'running',
    started_at        timestamptz  NOT NULL DEFAULT now(),
    finished_at       timestamptz  NULL,

    created_at        timestamptz  NOT NULL DEFAULT now(),
    created_by        uuid         NULL REFERENCES core.users(id) ON DELETE SET NULL,

    CONSTRAINT fk_batch_warehouse FOREIGN KEY (tenant_id, warehouse_id)
        REFERENCES core.warehouses (tenant_id, id),
    CONSTRAINT uq_batch_tenant_id UNIQUE (tenant_id, id),

    CONSTRAINT chk_batch_status CHECK (status IN ('running', 'completed', 'failed')),
    CONSTRAINT chk_batch_sha    CHECK (file_sha256 ~ '^[0-9a-f]{64}$'),
    CONSTRAINT chk_batch_conteos CHECK (
        rows_read >= 0 AND rows_rejected >= 0 AND rows_rejected <= rows_read
    ),
    -- Un lote terminado tiene fecha de fin; uno en marcha, no.
    CONSTRAINT chk_batch_fin CHECK (
        (status = 'running' AND finished_at IS NULL)
     OR (status <> 'running' AND finished_at IS NOT NULL)
    )
);

COMMENT ON TABLE spatial.import_batches IS
    'Un lote de importacion del catalogo espacial. `file_sha256` con indice unico sobre los completados es la idempotencia de nivel 1: reimportar el mismo archivo se detecta ANTES de leer una fila.';

-- ⚠ El índice es PARCIAL sobre `completed`: un lote fallido no debe bloquear el
--   reintento del mismo archivo, que es justo lo que hay que poder hacer.
CREATE UNIQUE INDEX uq_batch_archivo ON spatial.import_batches
    (tenant_id, warehouse_id, file_sha256) WHERE status = 'completed';
CREATE INDEX idx_batch_wh ON spatial.import_batches (tenant_id, warehouse_id, started_at DESC);


CREATE TABLE spatial.import_row_errors (
    id           bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id     uuid         NOT NULL REFERENCES spatial.import_batches(id) ON DELETE CASCADE,
    tenant_id    uuid         NOT NULL REFERENCES core.tenants(id),

    row_number   integer      NOT NULL,
    reason_code  varchar(60)  NOT NULL,
    field_name   varchar(40)  NULL,
    -- El contenido crudo de la fila. Sin él, un rechazo no se puede investigar.
    raw_row      text         NULL,

    created_at   timestamptz  NOT NULL DEFAULT now(),

    CONSTRAINT chk_error_fila CHECK (row_number >= 1)
);

COMMENT ON TABLE spatial.import_row_errors IS
    'Una fila por rechazo, con su numero, su motivo y su contenido crudo. SOLO-ANADIR: sin politica de UPDATE ni DELETE, porque un registro de errores editable no es un registro de errores.';

CREATE INDEX idx_error_lote   ON spatial.import_row_errors (batch_id, row_number);
CREATE INDEX idx_error_motivo ON spatial.import_row_errors (batch_id, reason_code);


-- ── RLS ────────────────────────────────────────────────────────────────────
ALTER TABLE spatial.import_batches    ENABLE ROW LEVEL SECURITY;
ALTER TABLE spatial.import_batches    FORCE  ROW LEVEL SECURITY;
ALTER TABLE spatial.import_row_errors ENABLE ROW LEVEL SECURITY;
ALTER TABLE spatial.import_row_errors FORCE  ROW LEVEL SECURITY;

CREATE POLICY tenant_isolation ON spatial.import_batches
    AS RESTRICTIVE FOR ALL TO authenticated, olo_app
    USING (tenant_id = core.current_tenant_id())
    WITH CHECK (tenant_id = core.current_tenant_id());
CREATE POLICY warehouse_scope ON spatial.import_batches
    AS PERMISSIVE FOR ALL TO authenticated, olo_app
    USING (core.can_access_warehouse(warehouse_id))
    WITH CHECK (core.can_access_warehouse(warehouse_id));

CREATE POLICY tenant_isolation ON spatial.import_row_errors
    AS RESTRICTIVE FOR ALL TO authenticated, olo_app
    USING (tenant_id = core.current_tenant_id())
    WITH CHECK (tenant_id = core.current_tenant_id());
-- Lectura e inserción, nunca UPDATE ni DELETE: solo-añadir.
CREATE POLICY errores_read ON spatial.import_row_errors
    AS PERMISSIVE FOR SELECT TO authenticated, olo_app USING (true);
CREATE POLICY errores_insert ON spatial.import_row_errors
    AS PERMISSIVE FOR INSERT TO authenticated, olo_app WITH CHECK (true);

GRANT SELECT, INSERT, UPDATE ON spatial.import_batches TO olo_app;
GRANT SELECT, INSERT ON spatial.import_row_errors TO olo_app;
-- Solo-añadir también a nivel de privilegio, no solo de política.
REVOKE UPDATE, DELETE ON spatial.import_row_errors FROM olo_app;
REVOKE DELETE ON spatial.import_batches FROM olo_app;


-- ── Verificación ───────────────────────────────────────────────────────────
DO $$
DECLARE v_n int; v_rech boolean;
BEGIN
    SELECT count(1) INTO v_n FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
     WHERE n.nspname = 'spatial'
       AND c.relname IN ('import_batches', 'import_row_errors')
       AND c.relrowsecurity AND c.relforcerowsecurity;
    IF v_n <> 2 THEN RAISE EXCEPTION 'FORCE RLS falta en % tabla(s)', 2 - v_n; END IF;

    -- Solo-añadir, comprobado a nivel de privilegio.
    IF has_table_privilege('olo_app', 'spatial.import_row_errors', 'UPDATE')
       OR has_table_privilege('olo_app', 'spatial.import_row_errors', 'DELETE') THEN
        RAISE EXCEPTION 'import_row_errors debe ser SOLO-ANADIR para olo_app';
    END IF;
    IF has_table_privilege('olo_app', 'spatial.import_batches', 'DELETE') THEN
        RAISE EXCEPTION 'olo_app no debe poder borrar lotes de importacion';
    END IF;

    -- Un lote 'running' con finished_at es incoherente.
    v_rech := false;
    BEGIN
        INSERT INTO spatial.import_batches
            (tenant_id, warehouse_id, source_name, file_sha256, status, finished_at)
        VALUES (uuid_generate_v4(), uuid_generate_v4(), 'x', repeat('a', 64),
                'running', now());
    EXCEPTION WHEN check_violation THEN v_rech := true;
              WHEN foreign_key_violation THEN v_rech := true;
    END;
    IF NOT v_rech THEN RAISE EXCEPTION 'se acepto un lote running con finished_at'; END IF;

    -- Un sha256 que no lo es.
    v_rech := false;
    BEGIN
        INSERT INTO spatial.import_batches
            (tenant_id, warehouse_id, source_name, file_sha256)
        VALUES (uuid_generate_v4(), uuid_generate_v4(), 'x', 'no-es-un-hash');
    EXCEPTION WHEN check_violation THEN v_rech := true;
              WHEN foreign_key_violation THEN v_rech := true;
              WHEN string_data_right_truncation THEN v_rech := true;
    END;
    IF NOT v_rech THEN RAISE EXCEPTION 'se acepto un sha256 invalido'; END IF;

    -- Mas rechazos que filas leidas es imposible.
    v_rech := false;
    BEGIN
        INSERT INTO spatial.import_batches
            (tenant_id, warehouse_id, source_name, file_sha256, rows_read, rows_rejected)
        VALUES (uuid_generate_v4(), uuid_generate_v4(), 'x', repeat('b', 64), 5, 9);
    EXCEPTION WHEN check_violation THEN v_rech := true;
              WHEN foreign_key_violation THEN v_rech := true;
    END;
    IF NOT v_rech THEN RAISE EXCEPTION 'se aceptaron mas rechazos que filas leidas'; END IF;

    RAISE NOTICE
        'OK 0056: import_batches e import_row_errors · FORCE RLS · '
        'indice unico PARCIAL sobre completed (un lote fallido no bloquea el reintento) · '
        'row_errors solo-anadir por politica Y por privilegio · 3 CHECK probados';
END
$$;
